// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.1_@parcel+watcher@2.5.1_@types+node@22.13.11_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_5cx2njwgs7khn4vs3pcyfelhvm/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}