name: citycars
region: nyc

# Environment variables (configure in DO dashboard)
envs:
  - key: NODE_ENV
    value: production
  - key: GOOGLE_MAPS_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: FIREBASE_SERVICE_ACCOUNT
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_APP_ID
    scope: RUN_AND_BUILD_TIME
  - key: NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    scope: RUN_AND_BUILD_TIME

# Single web service with module federation
services:
  - name: web
    github:
      repo: your-username/citycars
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: pnpm build
    
    # Run configuration
    run_command: node .output/server/index.mjs
    
    # Resource allocation
    instance_count: 1
    instance_size_slug: basic-xxs  # Upgrade as needed
    
    # HTTP configuration
    http_port: 3000
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
      - path: /admin
