// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2025, 4:33:46 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/saicharan/Documents/GitHub/citycars/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/plugins/**/*.{js,ts,mjs}","/Users/saicharan/Documents/GitHub/citycars/composables/**/*.{js,ts,mjs}","/Users/saicharan/Documents/GitHub/citycars/utils/**/*.{js,ts,mjs}","/Users/saicharan/Documents/GitHub/citycars/pages/index.vue","/Users/saicharan/Documents/GitHub/citycars/pages/quote.vue","/Users/saicharan/Documents/GitHub/citycars/pages/contact-us.vue","/Users/saicharan/Documents/GitHub/citycars/pages/airport-taxis.vue","/Users/saicharan/Documents/GitHub/citycars/pages/wheel-chair-taxis.vue","/Users/saicharan/Documents/GitHub/citycars/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/saicharan/Documents/GitHub/citycars/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;