// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/4/2025, 7:43:15 pm
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Sathish/Source Code/citycars/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/plugins/**/*.{js,ts,mjs}","C:/Sathish/Source Code/citycars/composables/**/*.{js,ts,mjs}","C:/Sathish/Source Code/citycars/utils/**/*.{js,ts,mjs}","C:/Sathish/Source Code/citycars/pages/index.vue","C:/Sathish/Source Code/citycars/pages/quote.vue","C:/Sathish/Source Code/citycars/pages/contact-us.vue","C:/Sathish/Source Code/citycars/pages/SamplePage.vue","C:/Sathish/Source Code/citycars/pages/airport-taxis.vue","C:/Sathish/Source Code/citycars/pages/wheel-chair-taxis.vue","C:/Sathish/Source Code/citycars/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Sathish/Source Code/citycars/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;